/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OORestaurants;

import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import OORestaurants.Login;

/**
 *
 * @author Akshay Adekar
 */
public class OO_Restaurants extends javax.swing.JFrame {

    /** Creates new form OO_Restaurants */
    public OO_Restaurants() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblMeals = new javax.swing.JLabel();
        jlblFiletoFish = new javax.swing.JLabel();
        jtxtFiletOFish = new javax.swing.JTextField();
        jlblChickenBurger = new javax.swing.JLabel();
        jtxtChickenBurger = new javax.swing.JTextField();
        jlblChickenLegend = new javax.swing.JLabel();
        jtxtChickenLegend = new javax.swing.JTextField();
        jlblChickenBurgerMeal = new javax.swing.JLabel();
        jtxtChickenBurgerMeal = new javax.swing.JTextField();
        jlblBaconandCheeseBurger = new javax.swing.JLabel();
        jtxtBaconCheese = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlblCostofMeal = new javax.swing.JLabel();
        jtxtCostMeal = new javax.swing.JTextField();
        jlblCostofDrinks = new javax.swing.JLabel();
        jtxtCostDrinks = new javax.swing.JTextField();
        jlblTotalCostofItems = new javax.swing.JLabel();
        jtxtCostTotalCost = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jtxtMilkShake = new javax.swing.JTextField();
        jlblDrinks = new javax.swing.JLabel();
        jlblMilkShake = new javax.swing.JLabel();
        jtxtVanillaCone = new javax.swing.JTextField();
        jlblVanillaCone = new javax.swing.JLabel();
        jtxtClassicVanilla = new javax.swing.JTextField();
        jlblClassicVanilla = new javax.swing.JLabel();
        jtxtVanillaMilkShake = new javax.swing.JTextField();
        jlblVanillaMilkShake = new javax.swing.JLabel();
        jtxtChocMilkShake = new javax.swing.JTextField();
        jlblChocolateMilkShake = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jbtnTotal1 = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setPreferredSize(new java.awt.Dimension(1280, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblMeals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblMeals.setText("Meals");

        jlblFiletoFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblFiletoFish.setText("Filet-o-Fish");

        jtxtFiletOFish.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtFiletOFish.setText("0");

        jlblChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblChickenBurger.setText("Chicken Burger");

        jtxtChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtChickenBurger.setText("0");

        jlblChickenLegend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblChickenLegend.setText("Chicken Legend");

        jtxtChickenLegend.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtChickenLegend.setText("0");
        jtxtChickenLegend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenLegendActionPerformed(evt);
            }
        });

        jlblChickenBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblChickenBurgerMeal.setText("Chicken Burger Meal");

        jtxtChickenBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtChickenBurgerMeal.setText("0");

        jlblBaconandCheeseBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblBaconandCheeseBurger.setText("Bacon and Cheese Burger");

        jtxtBaconCheese.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBaconCheese.setText("0");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlblFiletoFish, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblChickenBurger, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblChickenLegend, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jlblChickenBurgerMeal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .add(jlblMeals, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jlblBaconandCheeseBurger))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jtxtChickenBurger)
                    .add(jtxtFiletOFish)
                    .add(jtxtChickenLegend)
                    .add(jtxtChickenBurgerMeal)
                    .add(jtxtBaconCheese, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .add(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jlblMeals, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jtxtFiletOFish)
                    .add(jlblFiletoFish, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(jtxtChickenBurger, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jtxtChickenLegend))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jlblChickenBurger, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jlblChickenLegend, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jlblChickenBurgerMeal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jtxtChickenBurgerMeal)
                        .add(1, 1, 1)))
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jtxtBaconCheese, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblBaconandCheeseBurger, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 420, 320));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblCostofMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostofMeal.setText("Cost of Meal");

        jtxtCostMeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jlblCostofDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostofDrinks.setText("Cost of Drinks");

        jtxtCostDrinks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCostDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostDrinksActionPerformed(evt);
            }
        });

        jlblTotalCostofItems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotalCostofItems.setText("Total Cost of Items");

        jtxtCostTotalCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlblCostofDrinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblTotalCostofItems, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblCostofMeal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 76, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jtxtCostMeal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .add(jtxtCostTotalCost, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .add(jtxtCostDrinks))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jlblCostofMeal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jlblCostofDrinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jlblTotalCostofItems, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jtxtCostTotalCost))
                        .addContainerGap())
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jtxtCostMeal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .add(18, 18, 18)
                        .add(jtxtCostDrinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(65, 65, 65))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 420, 170));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 66)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurant Billing System");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1062, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(148, 148, 148))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1370, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtMilkShake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtMilkShake.setText("0");

        jlblDrinks.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jlblDrinks.setText("Drinks");

        jlblMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblMilkShake.setText("Milk Shake");

        jtxtVanillaCone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtVanillaCone.setText("0");

        jlblVanillaCone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblVanillaCone.setText("Vanilla Cone");

        jtxtClassicVanilla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtClassicVanilla.setText("0");

        jlblClassicVanilla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblClassicVanilla.setText("Classic Vanilla");

        jtxtVanillaMilkShake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtVanillaMilkShake.setText("0");

        jlblVanillaMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblVanillaMilkShake.setText("Vanilla Milk Shake");

        jtxtChocMilkShake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtChocMilkShake.setText("0");

        jlblChocolateMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblChocolateMilkShake.setText("Chocolate Milk Shake");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(153, 153, 153)
                .add(jlblDrinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jlblMilkShake, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jtxtMilkShake, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jlblClassicVanilla, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jlblVanillaCone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jlblVanillaMilkShake, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jlblChocolateMilkShake, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 116, Short.MAX_VALUE)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jtxtVanillaCone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jtxtClassicVanilla, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jtxtVanillaMilkShake, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jtxtChocMilkShake, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jlblDrinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtxtMilkShake, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblMilkShake, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jtxtVanillaCone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblVanillaCone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtxtClassicVanilla, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblClassicVanilla, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtxtVanillaMilkShake, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblVanillaMilkShake, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblChocolateMilkShake, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtxtChocMilkShake, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(68, 68, 68))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 450, 320));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 140, 480, 580));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.setText("Tax");

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal.setText("SubTotal");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setText("Total");

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel8Layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jlblTax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblSubTotal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .add(jlblTotal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 164, Short.MAX_VALUE)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jtxtTax)
                    .add(jtxtSubTotal)
                    .add(jtxtTotal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .add(49, 49, 49))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtxtTax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblTax))
                .add(18, 18, 18)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jtxtSubTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblSubTotal))
                .add(18, 18, 18)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jtxtTotal)
                    .add(jPanel8Layout.createSequentialGroup()
                        .add(jlblTotal)
                        .add(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 450, 170));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jbtnTotal1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnTotal1.setText("Total");
        jbtnTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotal1ActionPerformed(evt);
            }
        });

        jbtnReceipt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBack.setText("Back");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jbtnTotal1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(63, 63, 63)
                .add(jbtnReceipt)
                .add(94, 94, 94)
                .add(jBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 113, Short.MAX_VALUE)
                .add(jbtnReset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(101, 101, 101)
                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(19, 19, 19))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jBack, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(1, 1, 1))
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jbtnTotal1)
                            .add(jbtnReceipt)
                            .add(jbtnReset)
                            .add(jButton4))))
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 880, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtChickenLegendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenLegendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenLegendActionPerformed

    private void jtxtCostDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostDrinksActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SubClass_Child iExit = new SubClass_Child();
        iExit.iExitSystem();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
    JTextField cleartext = null;
    for (Component c:jPanel4.getComponents()){
    if (c.getClass().toString().contains("javax.swing.JTextField")){
        cleartext = (JTextField)c;
        cleartext.setText("");
    }    
    } 
    //==============================================================================================
    for (Component c:jPanel1.getComponents()){
    if (c.getClass().toString().contains("javax.swing.JTextField")){
        cleartext = (JTextField)c;
        cleartext.setText("");
    }    
    } 
    
    //==================================================================================================
    
    for (Component c:jPanel2.getComponents()){
    if (c.getClass().toString().contains("javax.swing.JTextField")){
        cleartext = (JTextField)c;
        cleartext.setText("");
    }    
    } 
    //============================================================================================
    for (Component c:jPanel8.getComponents()){
    if (c.getClass().toString().contains("javax.swing.JTextField")){
        cleartext = (JTextField)c;
        cleartext.setText("");
    }    
    } 
    
    jtxtReceipt.setText(null);
    
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotal1ActionPerformed
        SubClass_Child ItemCost = new SubClass_Child();
        
        double iTax, iSubTotal, iTotal;
        
        ItemCost.Filet_O_Fish = ItemCost.pFilet_O_Fish * Double.parseDouble(jtxtFiletOFish.getText());
        ItemCost.ChickenBurger = ItemCost.pChickenBurger * Double.parseDouble(jtxtChickenBurger.getText());
        ItemCost.ChickenLegend = ItemCost.pChickenLegend * Double.parseDouble(jtxtChickenLegend.getText());
        ItemCost.ChickenBurgerM = ItemCost.pChickenBurgerM * Double.parseDouble(jtxtChickenBurgerMeal.getText());
        ItemCost.BaconCheeseBurger = ItemCost.pBaconCheeseBurger * Double.parseDouble(jtxtBaconCheese.getText());
        
        ItemCost.MilkShake = ItemCost.pMilkShake * Double.parseDouble(jtxtMilkShake.getText());
        ItemCost.VanillaCone = ItemCost.pVanillaCone * Double.parseDouble(jtxtVanillaCone.getText());
        ItemCost.ClasVanilla = ItemCost.pClasVanilla * Double.parseDouble(jtxtClassicVanilla.getText());
        ItemCost.VanMilkShake = ItemCost.pVanMilkShake * Double.parseDouble(jtxtVanillaMilkShake.getText());
        ItemCost.ChocMilkShake = ItemCost.pChocMilkShake * Double.parseDouble(jtxtChocMilkShake.getText());
        
        iSubTotal = ItemCost.GetAmount();
        iTax = ItemCost.cFindTax(iSubTotal);
        iTotal = iSubTotal + iTax;
        
        String SubTotal =String.format("Rs.%.2f", iSubTotal);
        jtxtSubTotal.setText(SubTotal);
        String Tax =String.format("Rs.%.2f", iTax);
        jtxtTax.setText(Tax);
        
        String Total =String.format("Rs.%.2f", iTotal);
        jtxtTotal.setText(Total);
        
        String Meal =String.format("Rs.%.2f", ItemCost.Meals);
        jtxtCostMeal.setText(Meal);
        
        String Drink =String.format("Rs.%.2f", ItemCost.Drinks);
        jtxtCostDrinks.setText(Drink);
        
        String TotalCostItems =String.format("Rs.%,2f",ItemCost.TotalofMD);
        jtxtCostTotalCost.setText(TotalCostItems);
        
    }//GEN-LAST:event_jbtnTotal1ActionPerformed

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
        // TODO add your handling code here:
        
        //==========================================================================================================
        int refs= 1325 +(int) (Math.random()*4238);
        
        //==========================================================================================================
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-yyyy");
        Tdate.format(timer.getTime());
        
        
                jtxtReceipt.append("\tRestaurant Management System:\n"+
                        "References:\t\t\t" + refs +
                "\n======================================================================\n" +
                        "Meals:\t\t" +jtxtCostMeal.getText() + "\n\n" + 
                        "Drinks:\t\t" + jtxtCostDrinks.getText() + "\n\n" + 
                        "Cost Items:" + jtxtCostTotalCost.getText() + "\n\n" + 
                "\n======================================================================\n" + "\n\n" +
                        "Tax:\t\t" + jtxtTax.getText() + "\n\n" + 
                        "SubTotal:\t\t" + jtxtSubTotal.getText() + "\n\n" + 
                        "Total:\t\t" + jtxtTotal.getText() + "\n" +
                
                 "====================================================================" + 
                        "\nDate: " + Tdate.format(timer.getTime()) + 
                        "\nTime :" + tTime.format(timer.getTime()) +
                        "\n\n\t Thank you");
                
        
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        Login Info = new Login();
        Info.setVisible(true);
    }//GEN-LAST:event_jBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OO_Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBack;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal1;
    private javax.swing.JLabel jlblBaconandCheeseBurger;
    private javax.swing.JLabel jlblChickenBurger;
    private javax.swing.JLabel jlblChickenBurgerMeal;
    private javax.swing.JLabel jlblChickenLegend;
    private javax.swing.JLabel jlblChocolateMilkShake;
    private javax.swing.JLabel jlblClassicVanilla;
    private javax.swing.JLabel jlblCostofDrinks;
    private javax.swing.JLabel jlblCostofMeal;
    private javax.swing.JLabel jlblDrinks;
    private javax.swing.JLabel jlblFiletoFish;
    private javax.swing.JLabel jlblMeals;
    private javax.swing.JLabel jlblMilkShake;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblTotalCostofItems;
    private javax.swing.JLabel jlblVanillaCone;
    private javax.swing.JLabel jlblVanillaMilkShake;
    private javax.swing.JTextField jtxtBaconCheese;
    private javax.swing.JTextField jtxtChickenBurger;
    private javax.swing.JTextField jtxtChickenBurgerMeal;
    private javax.swing.JTextField jtxtChickenLegend;
    private javax.swing.JTextField jtxtChocMilkShake;
    private javax.swing.JTextField jtxtClassicVanilla;
    private javax.swing.JTextField jtxtCostDrinks;
    private javax.swing.JTextField jtxtCostMeal;
    private javax.swing.JTextField jtxtCostTotalCost;
    private javax.swing.JTextField jtxtFiletOFish;
    private javax.swing.JTextField jtxtMilkShake;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtVanillaCone;
    private javax.swing.JTextField jtxtVanillaMilkShake;
    // End of variables declaration//GEN-END:variables

}
